# Generated by Django 3.2 on 2022-10-11 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='exp',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
