# Generated by Django 3.2 on 2022-10-12 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_data_exp'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='expenses_monthly',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='income_monthly',
            field=models.IntegerField(default=0),
        ),
    ]
